name: CI/CD

on:
  push:
    tags: ["v*"]
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy rustfmt
      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Format
        run: cargo fmt -- --check
      - name: Run build
        run: cargo build --verbose

  macos:
    name: MacOS Wheels
    runs-on: macos-latest
    needs: [check]
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i 3.9 -i 3.10 -i 3.11 -i 3.12 -i 3.13 -i 3.14 -m ltc-py/Cargo.toml
          sccache: "true"
      - name: Install built wheel
        if: matrix.target == 'aarch64'
        run: |
          pip install ltcpy --no-index --find-links dist --force-reinstall
          python -c "import ltcpy"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.target }}-ltcpy
          path: dist

  windows:
    name: Windows Wheels
    runs-on: windows-latest
    needs: [check]
    strategy:
      matrix:
        target: [x64, x86]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i 3.9 -i 3.10 -i 3.11 -i 3.12 -i 3.13 -i 3.14 -m ltc-py/Cargo.toml
          sccache: "true"
      - name: Install built wheel
        if: matrix.target == 'x86_64'
        run: |
          pip install ltcpy --no-index --find-links dist --force-reinstall
          python -c "import ltcpy"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.target }}-ltcpy
          path: dist

  linux:
    name: Linux Wheels
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      matrix:
        target: [x86_64, x86, i686, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist -i 3.9 -i 3.10 -i 3.11 -i 3.12 -i 3.13 -i 3.14 -m ltc-py/Cargo.toml
          sccache: "true"
      - name: Install built wheel
        if: matrix.target == 'x86_64'
        run: |
          pip install ltcpy --no-index --find-links dist --force-reinstall
          python -c "import ltcpy"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}-ltcpy
          path: dist

  python:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux, windows, macos]
    environment: release
    steps:
      - uses: actions/download-artifact@v5
        with:
          workflow: build.yml
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing wheels-*/*

  rust:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [check]
    if: startsWith(github.ref, 'refs/tags/')
    environment: release
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v5
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
